import React, { useState } from "react";
import { Link } from "react-router-dom";

const Scholarships = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("all");
  const [filterLevel, setFilterLevel] = useState("all");
  const [showChecklist, setShowChecklist] = useState(false);
  const [selectedScholarship, setSelectedScholarship] = useState(null);
  const [showModal, setShowModal] = useState(false);

  const scholarships = [
    {
      id: 1,
      title: "HELB Undergraduate Scholarship",
      provider: "Higher Education Loans Board",
      type: "government",
      level: "undergraduate",
      amount: "Up to Ksh 60,000 per year",
      deadline: "2026-03-30",
      description: "Government sponsorship for Kenyan undergraduate students in public universities.",
      requirements: ["KCSE mean grade C+", "Admitted to public university", "Financial need"],
      status: "open",
      image: "🏛️",
      applicationLink: "https://www.helb.co.ke",
      contact: "helb@helb.co.ke | 020-1234567"
    },
    {
      id: 2,
      title: "HELB Scholarship + Loan",
      provider: "Higher Education Loans Board",
      type: "government",
      level: "undergraduate",
      amount: "Up to Ksh 80,000 per year (Scholarship + Loan combo)",
      deadline: "2026-04-15",
      description: "Combined scholarship and loan package for Kenyan students in public universities and TVET institutions.",
      requirements: ["KCSE mean grade C+", "Admitted to public university or TVET", "Financial need assessment", "First-time applicant"],
      status: "open",
      image: "💰",
      applicationLink: "https://www.helb.co.ke",
      contact: "helb@helb.co.ke | 020-1234567"
    },
    {
      id: 3,
      title: "Government Scholarship through HEF",
      provider: "Higher Education Fund (HEF)",
      type: "government",
      level: "undergraduate",
      amount: "Full tuition + Up to Ksh 30,000 stipend",
      deadline: "2026-05-30",
      description: "Government-funded scholarship for needy and meritorious students in public universities.",
      requirements: ["KCSE mean grade B", "Household income below Ksh 30,000/month", "Admitted to public university", "Strong academic record"],
      status: "open",
      image: "🇰🇪",
      applicationLink: "https://www.education.go.ke",
      contact: "hef@education.go.ke | 020-1234567"
    }
  ];

  const filteredScholarships = scholarships.filter(scholarship => {
    const matchesSearch = scholarship.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          scholarship.provider.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesType = filterType === "all" || scholarship.type === filterType;
    const matchesLevel = filterLevel === "all" || scholarship.level === filterLevel;
    return matchesSearch && matchesType && matchesLevel;
  });

  const handleViewDetails = (scholarship) => {
    setSelectedScholarship(scholarship);
    setShowModal(true);
    document.body.style.overflow = "hidden";
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setSelectedScholarship(null);
    document.body.style.overflow = "auto";
  };

  const handleDownloadChecklist = () => {
    const checklistContent = `SCHOLARSHIP DOCUMENT CHECKLIST
================================

ESSENTIAL DOCUMENTS:
✓ KCSE/KCPE Certificate
✓ National ID or Birth Certificate
✓ University/College Admission Letter
✓ Bank Statements (for means testing)
✓ Passport Size Photos (2 copies)

SUPPORTING DOCUMENTS:
✓ Recommendation Letters (2-3)
✓ Personal Statement/Essay
✓ Community Service Certificate
✓ Leadership Certificates
✓ Academic Transcripts (if applicable)
✓ Parent/Guardian ID copies
✓ Death Certificate (if orphaned)

TIPS BEFORE APPLYING:
1. Read all requirements carefully
2. Check deadlines - apply early
3. Make copies of all documents
4. Get recommendation letters early
5. Proofread your application

Generated by EduFund Kenya - Scholarship & Bursary Finder
Visit us at: www.edufundkenya.com
Date: ${new Date().toLocaleDateString()}
`;

    const blob = new Blob([checklistContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `scholarship_checklist_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    alert("Checklist downloaded successfully!");
  };

  const getStatusBadge = (status) => {
    switch(status) {
      case "open":
        return <span className="bg-green-100 text-green-600 px-2 py-1 rounded text-xs font-semibold">Open</span>;
      case "closing":
        return <span className="bg-yellow-100 text-yellow-600 px-2 py-1 rounded text-xs font-semibold">Closing Soon</span>;
      case "upcoming":
        return <span className="bg-blue-100 text-blue-600 px-2 py-1 rounded text-xs font-semibold">Upcoming</span>;
      default:
        return <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded text-xs font-semibold">Closed</span>;
    }
  };

  const getTypeBadge = (type) => {
    switch(type) {
      case "government":
        return <span className="bg-blue-100 text-blue-600 px-2 py-1 rounded text-xs font-semibold">Government</span>;
      case "private":
        return <span className="bg-purple-100 text-purple-600 px-2 py-1 rounded text-xs font-semibold">Private</span>;
      case "international":
        return <span className="bg-red-100 text-red-600 px-2 py-1 rounded text-xs font-semibold">International</span>;
      case "county":
        return <span className="bg-green-100 text-green-600 px-2 py-1 rounded text-xs font-semibold">County</span>;
      default:
        return <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded text-xs font-semibold">Other</span>;
    }
  };

  const handleRegisterWebinar = (webinarTitle) => {
    alert(`You have successfully registered for "${webinarTitle}"!\n\nA confirmation email will be sent to your registered email address.`);
  };

  return (
    <div className="bg-gray-50 min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-600 to-blue-800 text-white py-16">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-4">Find Your Perfect Scholarship</h1>
          <p className="text-xl mb-8">Discover hundreds of scholarships tailored for Kenyan students</p>
        </div>
      </section>

      {/* Search and Filter Section */}
      <section className="container mx-auto px-4 -mt-8">
        <div className="bg-white rounded-lg shadow-lg p-6">
          <div className="mb-6">
            <input
              type="text"
              placeholder="Search by scholarship name or provider..."
              className="w-full p-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          
          <div className="grid md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Scholarship Type</label>
              <select
                className="w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={filterType}
                onChange={(e) => setFilterType(e.target.value)}
              >
                <option value="all">All Types</option>
                <option value="government">Government</option>
                <option value="private">Private</option>
                <option value="international">International</option>
                <option value="county">County</option>
              </select>
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Education Level</label>
              <select
                className="w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={filterLevel}
                onChange={(e) => setFilterLevel(e.target.value)}
              >
                <option value="all">All Levels</option>
                <option value="highschool">High School</option>
                <option value="undergraduate">Undergraduate</option>
                <option value="postgraduate">Postgraduate</option>
              </select>
            </div>
          </div>
        </div>
      </section>

      {/* Results Section */}
      <section className="container mx-auto px-4 py-12">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-gray-800">
            Available Scholarships ({filteredScholarships.length})
          </h2>
          <p className="text-gray-600">Showing all opportunities</p>
        </div>

        {filteredScholarships.length === 0 ? (
          <div className="bg-white rounded-lg shadow p-12 text-center">
            <div className="text-6xl mb-4">🔍</div>
            <h3 className="text-xl font-bold text-gray-800 mb-2">No scholarships found</h3>
            <p className="text-gray-600">Try adjusting your search or filter criteria</p>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredScholarships.map((scholarship) => (
              <div key={scholarship.id} className="bg-white rounded-lg shadow-lg overflow-hidden hover:shadow-xl transition">
                <div className="p-6">
                  <div className="flex justify-between items-start mb-3">
                    <div className="text-4xl">{scholarship.image}</div>
                    <div className="flex gap-2">
                      {getStatusBadge(scholarship.status)}
                      {getTypeBadge(scholarship.type)}
                    </div>
                  </div>
                  
                  <h3 className="text-xl font-bold text-gray-800 mb-2">{scholarship.title}</h3>
                  <p className="text-blue-600 text-sm mb-2">{scholarship.provider}</p>
                  <p className="text-gray-600 text-sm mb-3">{scholarship.description}</p>
                  
                  <div className="space-y-2 mb-4">
                    <p className="text-sm text-gray-600">💰 <span className="font-semibold">Amount:</span> {scholarship.amount}</p>
                    <p className="text-sm text-gray-600">📅 <span className="font-semibold">Deadline:</span> {new Date(scholarship.deadline).toLocaleDateString()}</p>
                    <p className="text-sm text-gray-600">🎓 <span className="font-semibold">Level:</span> {scholarship.level}</p>
                  </div>
                  
                  <button 
                    onClick={() => handleViewDetails(scholarship)}
                    className="block w-full bg-blue-600 text-white text-center px-4 py-2 rounded-lg hover:bg-blue-700 transition"
                  >
                    View Details
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* Scholarship Details Modal */}
      {showModal && selectedScholarship && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50">
          <div className="bg-white rounded-lg shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            {/* Modal Header */}
            <div className="sticky top-0 bg-gradient-to-r from-blue-600 to-blue-800 text-white p-6 rounded-t-lg">
              <div className="flex justify-between items-start">
                <div className="flex items-center gap-3">
                  <span className="text-4xl">{selectedScholarship.image}</span>
                  <div>
                    <h2 className="text-2xl font-bold">{selectedScholarship.title}</h2>
                    <p className="text-blue-200 text-sm">{selectedScholarship.provider}</p>
                  </div>
                </div>
                <button
                  onClick={handleCloseModal}
                  className="text-white hover:text-gray-200 transition text-2xl"
                >
                  ×
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="p-6">
              {/* Status Badges */}
              <div className="flex flex-wrap gap-2 mb-4">
                {getStatusBadge(selectedScholarship.status)}
                {getTypeBadge(selectedScholarship.type)}
                <span className="bg-gray-100 text-gray-600 px-2 py-1 rounded text-xs font-semibold">
                  {selectedScholarship.level}
                </span>
              </div>

              {/* Description */}
              <div className="mb-4">
                <h3 className="text-lg font-bold text-gray-800 mb-2">About this Scholarship</h3>
                <p className="text-gray-600">{selectedScholarship.description}</p>
              </div>

              {/* Details Grid */}
              <div className="grid md:grid-cols-2 gap-4 mb-4">
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-sm text-gray-500">💰 Amount</p>
                  <p className="font-bold text-gray-800">{selectedScholarship.amount}</p>
                </div>
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-sm text-gray-500">📅 Deadline</p>
                  <p className="font-bold text-gray-800">{new Date(selectedScholarship.deadline).toLocaleDateString()}</p>
                </div>
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-sm text-gray-500">🎓 Education Level</p>
                  <p className="font-bold text-gray-800 capitalize">{selectedScholarship.level}</p>
                </div>
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-sm text-gray-500">📋 Status</p>
                  <p className="font-bold text-gray-800 capitalize">{selectedScholarship.status}</p>
                </div>
              </div>

              {/* Requirements */}
              <div className="mb-4">
                <h3 className="text-lg font-bold text-gray-800 mb-2">Requirements</h3>
                <ul className="list-disc list-inside space-y-1">
                  {selectedScholarship.requirements.map((req, index) => (
                    <li key={index} className="text-gray-600">{req}</li>
                  ))}
                </ul>
              </div>

              {/* Contact Information */}
              {selectedScholarship.contact && (
                <div className="mb-4">
                  <h3 className="text-lg font-bold text-gray-800 mb-2">Contact Information</h3>
                  <p className="text-gray-600">{selectedScholarship.contact}</p>
                </div>
              )}

              {/* Action Buttons */}
              <div className="flex flex-wrap gap-3 mt-6 pt-4 border-t border-gray-200">
                <button
                  onClick={() => {
                    if (selectedScholarship.applicationLink) {
                      window.open(selectedScholarship.applicationLink, '_blank');
                    } else {
                      alert("Application link will be available soon. Please check the provider's website for more information.");
                    }
                  }}
                  className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition font-semibold"
                >
                  Apply Now
                </button>
                <button
                  onClick={handleDownloadChecklist}
                  className="flex-1 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition font-semibold"
                >
                  📥 Download Checklist
                </button>
                <button
                  onClick={handleCloseModal}
                  className="flex-1 bg-gray-300 text-gray-700 px-4 py-2 rounded-lg hover:bg-gray-400 transition font-semibold"
                >
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Upcoming Webinars & Events */}
      <section className="bg-gradient-to-r from-purple-600 to-pink-600 text-white py-12">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4">Upcoming Scholarship Webinars</h2>
          <p className="text-center text-purple-100 mb-8">Learn from experts and increase your chances of winning scholarships</p>
          
          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            <div className="bg-white/10 backdrop-blur rounded-lg p-6 border border-white/20">
              <div className="text-3xl mb-3">🎓</div>
              <h3 className="text-xl font-bold mb-2">How to Write a Winning Scholarship Essay</h3>
              <p className="text-sm mb-2">📅 March 28, 2026 | 3:00 PM EAT</p>
              <p className="text-sm mb-4">👥 Free - Limited Slots</p>
              <button 
                onClick={() => handleRegisterWebinar("How to Write a Winning Scholarship Essay")}
                className="bg-white text-purple-600 px-4 py-2 rounded-lg font-semibold hover:bg-gray-100 transition w-full"
              >
                Register Now →
              </button>
            </div>
            
            <div className="bg-white/10 backdrop-blur rounded-lg p-6 border border-white/20">
              <div className="text-3xl mb-3">📝</div>
              <h3 className="text-xl font-bold mb-2">Understanding HELB Loan Application</h3>
              <p className="text-sm mb-2">📅 April 5, 2026 | 2:00 PM EAT</p>
              <p className="text-sm mb-4">👥 Free - Live Q&A</p>
              <button 
                onClick={() => handleRegisterWebinar("Understanding HELB Loan Application")}
                className="bg-white text-purple-600 px-4 py-2 rounded-lg font-semibold hover:bg-gray-100 transition w-full"
              >
                Register Now →
              </button>
            </div>
            
            <div className="bg-white/10 backdrop-blur rounded-lg p-6 border border-white/20">
              <div className="text-3xl mb-3">🌍</div>
              <h3 className="text-xl font-bold mb-2">International Scholarships Guide</h3>
              <p className="text-sm mb-2">📅 April 12, 2026 | 4:00 PM EAT</p>
              <p className="text-sm mb-4">👥 Free - With Certificate</p>
              <button 
                onClick={() => handleRegisterWebinar("International Scholarships Guide")}
                className="bg-white text-purple-600 px-4 py-2 rounded-lg font-semibold hover:bg-gray-100 transition w-full"
              >
                Register Now →
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Scholarship Categories by Field of Study */}
      <section className="container mx-auto px-4 py-12">
        <h2 className="text-3xl font-bold text-center text-gray-800 mb-4">Scholarships by Field of Study</h2>
        <p className="text-center text-gray-600 mb-8">Find opportunities in your area of interest</p>
        
        <div className="grid md:grid-cols-4 gap-4 max-w-5xl mx-auto">
          <Link to="/scholarships?field=science" className="bg-blue-50 p-4 rounded-lg text-center hover:bg-blue-100 transition cursor-pointer">
            <div className="text-3xl mb-2">🔬</div>
            <h3 className="font-bold text-gray-800">Science & Engineering</h3>
            <p className="text-sm text-gray-600">45+ scholarships</p>
          </Link>
          
          <Link to="/scholarships?field=business" className="bg-green-50 p-4 rounded-lg text-center hover:bg-green-100 transition cursor-pointer">
            <div className="text-3xl mb-2">💼</div>
            <h3 className="font-bold text-gray-800">Business & Economics</h3>
            <p className="text-sm text-gray-600">38+ scholarships</p>
          </Link>
          
          <Link to="/scholarships?field=arts" className="bg-purple-50 p-4 rounded-lg text-center hover:bg-purple-100 transition cursor-pointer">
            <div className="text-3xl mb-2">📚</div>
            <h3 className="font-bold text-gray-800">Arts & Humanities</h3>
            <p className="text-sm text-gray-600">22+ scholarships</p>
          </Link>
          
          <Link to="/scholarships?field=health" className="bg-yellow-50 p-4 rounded-lg text-center hover:bg-yellow-100 transition cursor-pointer">
            <div className="text-3xl mb-2">🩺</div>
            <h3 className="font-bold text-gray-800">Health & Medicine</h3>
            <p className="text-sm text-gray-600">31+ scholarships</p>
          </Link>
        </div>
      </section>

      {/* Document Preparation Checklist */}
      <section className="bg-gray-100 py-12">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center text-gray-800 mb-4">Scholarship Document Checklist</h2>
          <p className="text-center text-gray-600 mb-8">Prepare these documents before applying</p>
          
          <div className="grid md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            <div className="bg-white p-6 rounded-lg shadow">
              <h3 className="font-bold text-lg mb-4 text-blue-600">Essential Documents</h3>
              <ul className="space-y-3">
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>KCSE/KCPE Certificate</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>National ID or Birth Certificate</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>University/College Admission Letter</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Bank Statements (for means testing)</span>
                </li>
              </ul>
            </div>
            
            <div className="bg-white p-6 rounded-lg shadow">
              <h3 className="font-bold text-lg mb-4 text-blue-600">Supporting Documents</h3>
              <ul className="space-y-3">
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Recommendation Letters (2-3)</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Personal Statement/Essay</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Community Service Certificate</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-500">✓</span>
                  <span>Leadership Certificates</span>
                </li>
              </ul>
            </div>
          </div>
          
          <div className="text-center mt-6">
            <button 
              onClick={handleDownloadChecklist}
              className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition"
            >
              📥 Download Full Checklist PDF
            </button>
          </div>
        </div>
      </section>

      {/* Latest Scholarship News & Updates */}
      <section className="container mx-auto px-4 py-12">
        <h2 className="text-3xl font-bold text-center text-gray-800 mb-4">Latest Scholarship News</h2>
        <p className="text-center text-gray-600 mb-8">Stay updated with the latest announcements and deadlines</p>
        
        <div className="grid md:grid-cols-3 gap-6">
          <div className="bg-white rounded-lg shadow p-6 hover:shadow-lg transition">
            <div className="flex items-center gap-2 mb-3">
              <span className="bg-red-100 text-red-600 text-xs px-2 py-1 rounded">New</span>
              <span className="text-gray-500 text-sm">March 15, 2026</span>
            </div>
            <h3 className="font-bold text-lg mb-2">New Scholarship Program Launched for STEM Students</h3>
            <p className="text-gray-600 text-sm mb-3">The Ministry of Education announces 500 new scholarships for female STEM students.</p>
            <Link to="/news/1" className="text-blue-600 text-sm hover:underline">Read more →</Link>
          </div>
          
          <div className="bg-white rounded-lg shadow p-6 hover:shadow-lg transition">
            <div className="flex items-center gap-2 mb-3">
              <span className="bg-yellow-100 text-yellow-600 text-xs px-2 py-1 rounded">Deadline</span>
              <span className="text-gray-500 text-sm">March 10, 2026</span>
            </div>
            <h3 className="font-bold text-lg mb-2">HELB Application Deadline Extended</h3>
            <p className="text-gray-600 text-sm mb-3">HELB extends loan application deadline to April 30th, 2026.</p>
            <Link to="/news/2" className="text-blue-600 text-sm hover:underline">Read more →</Link>
          </div>
          
          <div className="bg-white rounded-lg shadow p-6 hover:shadow-lg transition">
            <div className="flex items-center gap-2 mb-3">
              <span className="bg-green-100 text-green-600 text-xs px-2 py-1 rounded">Success</span>
              <span className="text-gray-500 text-sm">March 5, 2026</span>
            </div>
            <h3 className="font-bold text-lg mb-2">5,000 Students Receive County Bursaries</h3>
            <p className="text-gray-600 text-sm mb-3">Counties disburse Ksh 150M in bursaries for needy students.</p>
            <Link to="/news/3" className="text-blue-600 text-sm hover:underline">Read more →</Link>
          </div>
        </div>
        
        <div className="text-center mt-8">
          <Link to="/news" className="inline-block border-2 border-blue-600 text-blue-600 px-6 py-2 rounded-lg font-semibold hover:bg-blue-600 hover:text-white transition">
            View All News
          </Link>
        </div>
      </section>

      {/* Tips Section */}
      <section className="bg-blue-50 py-12">
        <div className="container mx-auto px-4">
          <h2 className="text-2xl font-bold text-center text-gray-800 mb-8">Tips for Scholarship Success</h2>
          <div className="grid md:grid-cols-4 gap-6">
            <div className="bg-white p-6 rounded-lg shadow text-center">
              <div className="text-3xl mb-3">📝</div>
              <h3 className="font-bold mb-2">Start Early</h3>
              <p className="text-gray-600 text-sm">Begin your scholarship search at least 6 months before your intended start date.</p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow text-center">
              <div className="text-3xl mb-3">📄</div>
              <h3 className="font-bold mb-2">Prepare Documents</h3>
              <p className="text-gray-600 text-sm">Keep academic certificates, recommendation letters, and ID ready.</p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow text-center">
              <div className="text-3xl mb-3">✍️</div>
              <h3 className="font-bold mb-2">Write Strong Essays</h3>
              <p className="text-gray-600 text-sm">Tailor your personal statement to each scholarship's requirements.</p>
            </div>
            <div className="bg-white p-6 rounded-lg shadow text-center">
              <div className="text-3xl mb-3">🎯</div>
              <h3 className="font-bold mb-2">Apply to Multiple</h3>
              <p className="text-gray-600 text-sm">Increase your chances by applying to as many as you qualify for.</p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="container mx-auto px-4 py-12">
        <h2 className="text-2xl font-bold text-center text-gray-800 mb-8">Frequently Asked Questions</h2>
        <div className="max-w-3xl mx-auto space-y-4">
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-bold text-lg mb-2">How do I know if I'm eligible?</h3>
            <p className="text-gray-600">Each scholarship has specific eligibility criteria. Check the requirements carefully before applying.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-bold text-lg mb-2">Can I apply for multiple scholarships?</h3>
            <p className="text-gray-600">Yes! You can apply for as many scholarships as you qualify for.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-bold text-lg mb-2">What documents do I need?</h3>
            <p className="text-gray-600">Common documents include KCSE certificate, admission letter, ID, bank statements, and recommendation letters.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h3 className="font-bold text-lg mb-2">When will I know the results?</h3>
            <p className="text-gray-600">Results timelines vary by scholarship. Check each scholarship's page for specific dates.</p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Scholarships;